/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacies/{pharmacyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacies/{pharmacyId}/drugs/{drugId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs/{drugId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UploadResponse: {
            /** Format: int64 */
            id?: number;
            originalName?: string;
            contentType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            url?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PriceReportCreateRequest: {
            /** Format: int64 */
            pharmacyId: number;
            /** Format: int64 */
            drugId: number;
            /** Format: int32 */
            price: number;
            /** Format: date */
            purchasedAt?: string;
            /** Format: int64 */
            receiptFileId?: number;
            memo?: string;
        };
        PriceReportResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            pharmacyId?: number;
            /** Format: int64 */
            drugId?: number;
            /** Format: int32 */
            price?: number;
            /** Format: date */
            purchasedAt?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "HIDDEN" | "REJECTED";
            flagged?: boolean;
            /** @enum {string} */
            flagReason?: "OUTLIER_HIGH" | "OUTLIER_LOW" | "DUPLICATE" | "MANUAL";
            /** Format: date-time */
            createdAt?: string;
            warning?: string;
            updatedStat?: components["schemas"]["UpdatedStat"];
        };
        UpdatedStat: {
            /** Format: int32 */
            repPrice?: number;
            /** Format: int32 */
            minPrice?: number;
            /** Format: int32 */
            maxPrice?: number;
            /** Format: int32 */
            avgPrice?: number;
            /** Format: int32 */
            reportCount?: number;
            /** Format: date */
            lastReportedAt?: string;
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            nickname: string;
        };
        SignupResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            nickname?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            /** Format: date-time */
            createdAt?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LoginResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            expiresIn?: number;
            user?: components["schemas"]["UserSummary"];
        };
        UserSummary: {
            /** Format: int64 */
            id?: number;
            nickname?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        DrugInfo: {
            /** Format: int64 */
            id?: number;
            displayName?: string;
            packageUnit?: string;
            imageUrl?: string;
        };
        PharmacyInfo: {
            /** Format: int64 */
            id?: number;
            name?: string;
            addressRoad?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            phone?: string;
        };
        PriceInfo: {
            /** Format: int32 */
            repPrice?: number;
            /** Format: int32 */
            minPrice?: number;
            /** Format: int32 */
            avgPrice?: number;
            /** Format: int32 */
            savingVsCandidateAvg?: number;
            /** Format: int32 */
            reportCount?: number;
            /** Format: date */
            lastReportedAt?: string;
            /** Format: int64 */
            daysSinceLastReport?: number;
        };
        QueryInfo: {
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            /** Format: int32 */
            radius?: number;
            sort?: string;
            locationSource?: string;
        };
        ScoreBreakdown: {
            /** Format: double */
            priceScore?: number;
            /** Format: double */
            distanceScore?: number;
            /** Format: double */
            freshnessScore?: number;
            weights?: components["schemas"]["Weights"];
        };
        SearchResponse: {
            drug?: components["schemas"]["DrugInfo"];
            query?: components["schemas"]["QueryInfo"];
            summary?: components["schemas"]["SearchSummary"];
            /** @enum {string} */
            dataSource?: "SEED" | "MIXED" | "USER";
            results?: components["schemas"]["SearchResultItem"][];
            suggestion?: components["schemas"]["SearchSuggestion"];
        };
        SearchResultItem: {
            /** Format: int32 */
            rank?: number;
            recommended?: boolean;
            pharmacy?: components["schemas"]["PharmacyInfo"];
            price?: components["schemas"]["PriceInfo"];
            /** Format: int64 */
            distanceM?: number;
            /** Format: double */
            score?: number;
            scoreBreakdown?: components["schemas"]["ScoreBreakdown"];
            badges?: ("LOWEST_PRICE" | "LOW_CONFIDENCE" | "STALE_DATA" | "NEAREST")[];
        };
        SearchSuggestion: {
            type?: string;
            /** Format: int32 */
            recommendedRadius?: number;
            /** Format: int64 */
            estimatedCount?: number;
        };
        SearchSummary: {
            /** Format: int32 */
            resultCount?: number;
            /** Format: int32 */
            candidateAvgPrice?: number;
            /** Format: int32 */
            candidateMinPrice?: number;
            /** Format: int32 */
            candidateMaxPrice?: number;
            /** Format: int32 */
            maxSaving?: number;
        };
        Weights: {
            /** Format: double */
            price?: number;
            /** Format: double */
            distance?: number;
            /** Format: double */
            freshness?: number;
        };
        RegionGroupResponse: {
            sido?: string;
            sigungus?: components["schemas"]["SigunguItem"][];
        };
        SigunguItem: {
            code?: string;
            sigungu?: string;
            /** Format: double */
            centerLat?: number;
            /** Format: double */
            centerLng?: number;
            /** Format: int64 */
            pharmacyCount?: number;
        };
        Drug: {
            /** Format: int64 */
            id?: number;
            displayName?: string;
            packageUnit?: string;
        };
        PageResponsePriceReportListItemResponse: {
            content?: components["schemas"]["PriceReportListItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        Pharmacy: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        PriceReportListItemResponse: {
            /** Format: int64 */
            id?: number;
            pharmacy?: components["schemas"]["Pharmacy"];
            drug?: components["schemas"]["Drug"];
            /** Format: int32 */
            price?: number;
            /** Format: date */
            purchasedAt?: string;
            reporter?: components["schemas"]["Reporter"];
            /** @enum {string} */
            source?: "FORM" | "SEED" | "RECEIPT_OCR" | "PARTNER";
            /** @enum {string} */
            status?: "ACTIVE" | "HIDDEN" | "REJECTED";
            flagged?: boolean;
            hasReceipt?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        Reporter: {
            nickname?: string;
        };
        PageResponsePharmacySummaryResponse: {
            content?: components["schemas"]["PharmacySummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        PharmacySummaryResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            addressRoad?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            phone?: string;
            /** Format: int64 */
            distanceM?: number;
            region?: components["schemas"]["RegionInfo"];
        };
        RegionInfo: {
            code?: string;
            sido?: string;
            sigungu?: string;
        };
        DrugPriceItem: {
            /** Format: int64 */
            drugId?: number;
            displayName?: string;
            packageUnit?: string;
            /** Format: int32 */
            repPrice?: number;
            /** Format: int32 */
            minPrice?: number;
            /** Format: int32 */
            maxPrice?: number;
            /** Format: int32 */
            avgPrice?: number;
            /** Format: int32 */
            reportCount?: number;
            /** Format: date */
            lastReportedAt?: string;
            /** Format: int32 */
            nationalAvgPrice?: number;
            /** Format: int32 */
            diffFromNationalAvg?: number;
        };
        PharmacyDetailResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            addressRoad?: string;
            addressJibun?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            phone?: string;
            businessHours?: {
                [key: string]: string[];
            };
            /** Format: int64 */
            distanceM?: number;
            region?: components["schemas"]["RegionInfo"];
            drugPrices?: components["schemas"]["DrugPriceItem"][];
        };
        PriceHistoryResponse: {
            /** Format: int64 */
            pharmacyId?: number;
            /** Format: int64 */
            drugId?: number;
            points?: components["schemas"]["PricePoint"][];
        };
        PricePoint: {
            /** Format: date */
            purchasedAt?: string;
            /** Format: int32 */
            price?: number;
            flagged?: boolean;
        };
        DrugSummaryResponse: {
            /** Format: int64 */
            id?: number;
            itemSeq?: string;
            displayName?: string;
            name?: string;
            maker?: string;
            category?: string;
            form?: string;
            packageUnit?: string;
            imageUrl?: string;
            /** Format: int32 */
            nationalAvgPrice?: number;
            /** Format: int64 */
            pharmacyCount?: number;
        };
        PageResponseDrugSummaryResponse: {
            content?: components["schemas"]["DrugSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        DrugDetailResponse: {
            /** Format: int64 */
            id?: number;
            itemSeq?: string;
            displayName?: string;
            name?: string;
            maker?: string;
            category?: string;
            form?: string;
            packageUnit?: string;
            imageUrl?: string;
            priceStats?: components["schemas"]["PriceStats"];
        };
        PriceStats: {
            /** Format: int32 */
            nationalAvg?: number;
            /** Format: int32 */
            nationalMin?: number;
            /** Format: int32 */
            nationalMax?: number;
            /** Format: int64 */
            pharmacyCount?: number;
            /** Format: int64 */
            reportCount?: number;
        };
        MeResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            nickname?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            /** Format: int32 */
            reportCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload: {
        parameters: {
            query: {
                purpose: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                pharmacyId?: number;
                drugId?: number;
                mine?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponsePriceReportListItemResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceReportCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceReportResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SignupResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                drugId: number;
                lat?: number;
                lng?: number;
                regionCode?: string;
                radius?: number;
                sort?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegionGroupResponse"][];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                q?: string;
                lat?: number;
                lng?: number;
                radius?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponsePharmacySummaryResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: {
                lat?: number;
                lng?: number;
            };
            header?: never;
            path: {
                pharmacyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PharmacyDetailResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                pharmacyId: number;
                drugId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceHistoryResponse"];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                q?: string;
                category?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseDrugSummaryResponse"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drugId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DrugDetailResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
}
