/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
// T-21: /api/v1/pharmacies/{pharmacyId}·/history 두 엔드포인트는 SecurityConfig
// 미배선(T-23 전)으로 /v3/api-docs 자체가 401을 반환해 `npm run gen:api`로
// 재생성할 수 없었다. PharmacyDetailResponse.java/PriceHistoryResponse.java를
// 근거로 아래 스키마·경로를 수동으로 추가했다 — T-23 이후 gen:api로 재생성되면
// 이 주석과 함께 제거한다.

export interface paths {
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs/{drugId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacies/{pharmacyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pharmacyId: number;
            };
            cookie?: never;
        };
        get: operations["pharmacyDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacies/{pharmacyId}/drugs/{drugId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pharmacyId: number;
                drugId: number;
            };
            cookie?: never;
        };
        get: operations["pharmacyHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DrugInfo: {
            /** Format: int64 */
            id?: number;
            displayName?: string;
            packageUnit?: string;
            imageUrl?: string;
        };
        PharmacyInfo: {
            /** Format: int64 */
            id?: number;
            name?: string;
            addressRoad?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            phone?: string;
        };
        PriceInfo: {
            /** Format: int32 */
            repPrice?: number;
            /** Format: int32 */
            minPrice?: number;
            /** Format: int32 */
            avgPrice?: number;
            /** Format: int32 */
            savingVsCandidateAvg?: number;
            /** Format: int32 */
            reportCount?: number;
            /** Format: date */
            lastReportedAt?: string;
            /** Format: int64 */
            daysSinceLastReport?: number;
        };
        QueryInfo: {
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            /** Format: int32 */
            radius?: number;
            sort?: string;
            locationSource?: string;
        };
        ScoreBreakdown: {
            /** Format: double */
            priceScore?: number;
            /** Format: double */
            distanceScore?: number;
            /** Format: double */
            freshnessScore?: number;
            weights?: components["schemas"]["Weights"];
        };
        SearchResponse: {
            drug?: components["schemas"]["DrugInfo"];
            query?: components["schemas"]["QueryInfo"];
            summary?: components["schemas"]["SearchSummary"];
            /** @enum {string} */
            dataSource?: "SEED" | "MIXED" | "USER";
            results?: components["schemas"]["SearchResultItem"][];
            suggestion?: components["schemas"]["SearchSuggestion"];
        };
        SearchResultItem: {
            /** Format: int32 */
            rank?: number;
            recommended?: boolean;
            pharmacy?: components["schemas"]["PharmacyInfo"];
            price?: components["schemas"]["PriceInfo"];
            /** Format: int64 */
            distanceM?: number;
            /** Format: double */
            score?: number;
            scoreBreakdown?: components["schemas"]["ScoreBreakdown"];
            badges?: ("LOWEST_PRICE" | "LOW_CONFIDENCE" | "STALE_DATA" | "NEAREST")[];
        };
        SearchSuggestion: {
            type?: string;
            /** Format: int32 */
            recommendedRadius?: number;
            /** Format: int64 */
            estimatedCount?: number;
        };
        SearchSummary: {
            /** Format: int32 */
            resultCount?: number;
            /** Format: int32 */
            candidateAvgPrice?: number;
            /** Format: int32 */
            candidateMinPrice?: number;
            /** Format: int32 */
            candidateMaxPrice?: number;
            /** Format: int32 */
            maxSaving?: number;
        };
        Weights: {
            /** Format: double */
            price?: number;
            /** Format: double */
            distance?: number;
            /** Format: double */
            freshness?: number;
        };
        RegionGroupResponse: {
            sido?: string;
            sigungus?: components["schemas"]["SigunguItem"][];
        };
        SigunguItem: {
            code?: string;
            sigungu?: string;
            /** Format: double */
            centerLat?: number;
            /** Format: double */
            centerLng?: number;
            /** Format: int64 */
            pharmacyCount?: number;
        };
        DrugSummaryResponse: {
            /** Format: int64 */
            id?: number;
            itemSeq?: string;
            displayName?: string;
            name?: string;
            maker?: string;
            category?: string;
            form?: string;
            packageUnit?: string;
            imageUrl?: string;
            /** Format: int32 */
            nationalAvgPrice?: number;
            /** Format: int64 */
            pharmacyCount?: number;
        };
        PageResponseDrugSummaryResponse: {
            content?: components["schemas"]["DrugSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        DrugDetailResponse: {
            /** Format: int64 */
            id?: number;
            itemSeq?: string;
            displayName?: string;
            name?: string;
            maker?: string;
            category?: string;
            form?: string;
            packageUnit?: string;
            imageUrl?: string;
            priceStats?: components["schemas"]["PriceStats"];
        };
        PriceStats: {
            /** Format: int32 */
            nationalAvg?: number;
            /** Format: int32 */
            nationalMin?: number;
            /** Format: int32 */
            nationalMax?: number;
            /** Format: int64 */
            pharmacyCount?: number;
            /** Format: int64 */
            reportCount?: number;
        };
        PharmacyDetailResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            addressRoad?: string;
            addressJibun?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            phone?: string;
            businessHours?: {
                [key: string]: string[] | null;
            };
            /** Format: int64 */
            distanceM?: number;
            region?: components["schemas"]["RegionInfo"];
            drugPrices?: components["schemas"]["DrugPriceItem"][];
        };
        RegionInfo: {
            code?: string;
            sido?: string;
            sigungu?: string;
        };
        DrugPriceItem: {
            /** Format: int64 */
            drugId?: number;
            displayName?: string;
            packageUnit?: string;
            /** Format: int32 */
            repPrice?: number;
            /** Format: int32 */
            minPrice?: number;
            /** Format: int32 */
            maxPrice?: number;
            /** Format: int32 */
            avgPrice?: number;
            /** Format: int32 */
            reportCount?: number;
            /** Format: date */
            lastReportedAt?: string;
            /** Format: int32 */
            nationalAvgPrice?: number;
            /** Format: int32 */
            diffFromNationalAvg?: number;
        };
        PriceHistoryResponse: {
            /** Format: int64 */
            pharmacyId?: number;
            /** Format: int64 */
            drugId?: number;
            points?: components["schemas"]["PricePoint"][];
        };
        PricePoint: {
            /** Format: date */
            purchasedAt?: string;
            /** Format: int32 */
            price?: number;
            flagged?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query: {
                drugId: number;
                lat?: number;
                lng?: number;
                regionCode?: string;
                radius?: number;
                sort?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegionGroupResponse"][];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                q?: string;
                category?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseDrugSummaryResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drugId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DrugDetailResponse"];
                };
            };
        };
    };
    pharmacyDetail: {
        parameters: {
            query?: {
                lat?: number;
                lng?: number;
            };
            header?: never;
            path: {
                pharmacyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PharmacyDetailResponse"];
                };
            };
        };
    };
    pharmacyHistory: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                pharmacyId: number;
                drugId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceHistoryResponse"];
                };
            };
        };
    };
}
