/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs/{drugId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DrugInfo: {
            /** Format: int64 */
            id?: number;
            displayName?: string;
            packageUnit?: string;
            imageUrl?: string;
        };
        PharmacyInfo: {
            /** Format: int64 */
            id?: number;
            name?: string;
            addressRoad?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            phone?: string;
        };
        PriceInfo: {
            /** Format: int32 */
            repPrice?: number;
            /** Format: int32 */
            minPrice?: number;
            /** Format: int32 */
            avgPrice?: number;
            /** Format: int32 */
            savingVsCandidateAvg?: number;
            /** Format: int32 */
            reportCount?: number;
            /** Format: date */
            lastReportedAt?: string;
            /** Format: int64 */
            daysSinceLastReport?: number;
        };
        QueryInfo: {
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            /** Format: int32 */
            radius?: number;
            sort?: string;
            locationSource?: string;
        };
        ScoreBreakdown: {
            /** Format: double */
            priceScore?: number;
            /** Format: double */
            distanceScore?: number;
            /** Format: double */
            freshnessScore?: number;
            weights?: components["schemas"]["Weights"];
        };
        SearchResponse: {
            drug?: components["schemas"]["DrugInfo"];
            query?: components["schemas"]["QueryInfo"];
            summary?: components["schemas"]["SearchSummary"];
            /** @enum {string} */
            dataSource?: "SEED" | "MIXED" | "USER";
            results?: components["schemas"]["SearchResultItem"][];
            suggestion?: components["schemas"]["SearchSuggestion"];
        };
        SearchResultItem: {
            /** Format: int32 */
            rank?: number;
            recommended?: boolean;
            pharmacy?: components["schemas"]["PharmacyInfo"];
            price?: components["schemas"]["PriceInfo"];
            /** Format: int64 */
            distanceM?: number;
            /** Format: double */
            score?: number;
            scoreBreakdown?: components["schemas"]["ScoreBreakdown"];
            badges?: ("LOWEST_PRICE" | "LOW_CONFIDENCE" | "STALE_DATA" | "NEAREST")[];
        };
        SearchSuggestion: {
            type?: string;
            /** Format: int32 */
            recommendedRadius?: number;
            /** Format: int64 */
            estimatedCount?: number;
        };
        SearchSummary: {
            /** Format: int32 */
            resultCount?: number;
            /** Format: int32 */
            candidateAvgPrice?: number;
            /** Format: int32 */
            candidateMinPrice?: number;
            /** Format: int32 */
            candidateMaxPrice?: number;
            /** Format: int32 */
            maxSaving?: number;
        };
        Weights: {
            /** Format: double */
            price?: number;
            /** Format: double */
            distance?: number;
            /** Format: double */
            freshness?: number;
        };
        RegionGroupResponse: {
            sido?: string;
            sigungus?: components["schemas"]["SigunguItem"][];
        };
        SigunguItem: {
            code?: string;
            sigungu?: string;
            /** Format: double */
            centerLat?: number;
            /** Format: double */
            centerLng?: number;
            /** Format: int64 */
            pharmacyCount?: number;
        };
        DrugSummaryResponse: {
            /** Format: int64 */
            id?: number;
            itemSeq?: string;
            displayName?: string;
            name?: string;
            maker?: string;
            category?: string;
            form?: string;
            packageUnit?: string;
            imageUrl?: string;
            /** Format: int32 */
            nationalAvgPrice?: number;
            /** Format: int64 */
            pharmacyCount?: number;
        };
        PageResponseDrugSummaryResponse: {
            content?: components["schemas"]["DrugSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        DrugDetailResponse: {
            /** Format: int64 */
            id?: number;
            itemSeq?: string;
            displayName?: string;
            name?: string;
            maker?: string;
            category?: string;
            form?: string;
            packageUnit?: string;
            imageUrl?: string;
            priceStats?: components["schemas"]["PriceStats"];
        };
        PriceStats: {
            /** Format: int32 */
            nationalAvg?: number;
            /** Format: int32 */
            nationalMin?: number;
            /** Format: int32 */
            nationalMax?: number;
            /** Format: int64 */
            pharmacyCount?: number;
            /** Format: int64 */
            reportCount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query: {
                drugId: number;
                lat?: number;
                lng?: number;
                regionCode?: string;
                radius?: number;
                sort?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegionGroupResponse"][];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                q?: string;
                category?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseDrugSummaryResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drugId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DrugDetailResponse"];
                };
            };
        };
    };
}
