spring.application.name=miniProject1-backend

# --- Database (PostgreSQL / pharmaprice) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmaprice
spring.datasource.username=pharmaprice
spring.datasource.password=changeme
 
# --- JPA / Hibernate --- Flyway Migration선택해서 진행 
spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true 
logging.level.org.hibernate=info 
logging.level.org.hibernate.SQL=debug